[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[features]
default = ["sea-orm-impl", "sqlx-impl"]
sea-orm-impl = ["sea_orm_impl"]
sqlx-impl = ["sqlx_impl"]

[dependencies]
anyhow = { workspace = true }
domain = { path = "../domain" }
sea_orm_impl = { path = "repository/sea_orm_impl", optional = true }
sqlx_impl = { path = "repository/sqlx_impl", optional = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
sea-orm = { version = "1.1.1", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
sqlx = { workspace = true }
