[workspace]
members = [
    "crates/domain",
    "crates/sqlx_repository",
    "crates/app",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.100"
async-trait = "0.1"
sqlx = { version = "0.8.6", features = [ "postgres", "runtime-tokio", "tls-native-tls", "uuid" ] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"]}
uuid = { version = "1.18.1", features = ["v4"] }