[workspace]
members = [
    "crates/domain",
    "crates/sqlx_repository",
    "crates/sea_orm_repository",
    "crates/sqlx_app",
    "crates/sea_orm_app",
]
resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.100", features = ["std"] }
async-trait = "0.1"
futures = "0.3"
sqlx = { version = "0.8.6", features = [ "postgres", "runtime-tokio", "tls-native-tls", "uuid" ] }
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros"]}
uuid = { version = "1.18.1", features = ["v4"] }
