[package]
name = "application"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sea_orm_app"
path = "src/bin/sea_orm_app.rs"

[[bin]]
name = "sqlx_app"
path = "src/bin/sqlx_app.rs"

[dependencies]
anyhow = { workspace = true }
domain = { path = "../domain" }
sea_orm_impl = { path = "../infrastructure/repository/sea_orm_impl" }
sqlx = { workspace = true }
sqlx_impl = { path = "../infrastructure/repository/sqlx_impl" }
tokio = { workspace = true }
use_case = { path = "../use_case" }
uuid = { workspace = true }
