[package]
name = "sea_orm_app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "sea_orm_repository"
path = "src/main.rs"

[dependencies]
domain = { path = "../domain" }
sea_orm_repository = { path = "../sea_orm_repository" }
sea_orm_use_case = { path = "../sea_orm_use_case" }
anyhow = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
sea-orm = { version = "1.0", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }